import Image from "next/image";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, ArrowRight, CirclePause, FileDown, HelpCircle, KeyRound, Landmark, Radar, WalletCards } from "lucide-react";

export const dynamic = "force-dynamic";

const nav = [["getting-started", "Start here"], ["workspace", "Understand the workspace"], ["decisions", "Decision meanings"], ["payments", "Run a payment"], ["audit", "Audit evidence"], ["troubleshooting", "Troubleshooting"]];

export default function DocsPage() {
  return <div className="min-h-screen bg-[#080b09] text-white">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#080b09]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/"><Image src="/assay-logo.svg" alt="Assay" width={145} height={35} className="h-9 w-auto" /></Link><div className="flex items-center gap-4"><Link href="/" className="hidden items-center gap-2 text-sm font-bold text-zinc-300 sm:flex"><ArrowLeft className="h-4 w-4" />Overview</Link><Link href="/app" className="inline-flex items-center gap-2 rounded-full bg-[#a8d14a] px-5 py-2.5 text-sm font-extrabold text-zinc-950">Open workspace<ArrowRight className="h-4 w-4" /></Link></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-12 px-5 py-12 sm:px-8 lg:grid-cols-[250px_1fr] lg:py-16">
      <aside className="hidden lg:block"><div className="sticky top-28"><p className="mb-4 text-sm font-extrabold uppercase tracking-[.16em] text-[#a8d14a]">Operating guide</p><nav className="space-y-1">{nav.map(([id, label]) => <a key={id} href={`#${id}`} className="block rounded-lg px-3 py-2.5 text-sm font-semibold text-zinc-300 hover:bg-white/5 hover:text-white">{label}</a>)}</nav><div className="mt-8 rounded-xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-zinc-300"><strong className="text-white">Sandbox reminder</strong><br />Use only testnet MON and aUSDC. Never send real assets to a managed sandbox wallet.</div></div></aside>
      <main className="min-w-0 max-w-4xl">
        <section className="border-b border-white/10 pb-14"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#a8d14a]">Assay user guide</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">Run your first treasury decision.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-zinc-300">Assay watches verified stablecoin activity, decides whether it fits your operating policy, and gives your team a review queue for exceptions. This guide takes you from an empty account to a real Monad testnet transaction.</p></section>

        <GuideSection id="getting-started" eyebrow="5-minute setup" title="Start here: activate your workspace">
          <p>Create an account and choose <strong>Create workspace</strong>. Assay creates a managed testnet wallet and automatically configures Monad, Cleanverse, and aUSDC.</p>
          <div className="mt-8 space-y-4"><Instruction number="1" title="Save the recovery key">Copy it to a password manager. It is hidden by default and shown only during creation. Anyone with this key controls that test wallet.</Instruction><Instruction number="2" title="Verify the wallet">Open your workspace and press <strong>Verify identity</strong>. Complete the Cleanverse sandbox flow, then return and refresh.</Instruction><Instruction number="3" title="Get Monad testnet MON">Open <a href="https://faucet.monad.xyz/" target="_blank" rel="noreferrer" className="font-bold text-[#a8d14a] underline">the official Monad faucet</a> and send MON directly to the workspace wallet shown in Assay.</Instruction><Instruction number="4" title="Get aUSDC through Cleanverse">Copy the <strong>Cleanverse deposit address</strong> from Workspace Readiness. Open <a href="https://faucet.circle.com/?allow=true" target="_blank" rel="noreferrer" className="font-bold text-[#a8d14a] underline">the official Circle faucet</a>, select <strong>USDC</strong> and <strong>Monad Testnet</strong>, and paste the deposit address. Do not paste the workspace wallet.</Instruction><Instruction number="5" title="Wait and refresh">Cleanverse converts the deposited Circle USDC into aUSDC at the workspace wallet. Refresh after the transfer and conversion finish.</Instruction><Instruction number="6" title="Run a small payment">Send a test inbound transfer to the workspace address or enter a recipient and amount under Pay a supplier.</Instruction></div>
          <Callout icon={<AlertTriangle />} title="Do not fund a key shown in a screenshot">If a recovery key has been shared or screenshotted, consider that wallet compromised. Create a new workspace and use the new address.</Callout>
        </GuideSection>

        <GuideSection id="workspace" eyebrow="What you are looking at" title="The workspace is ordered by what needs attention">
          <div className="grid gap-5 sm:grid-cols-2"><Definition icon={<WalletCards />} title="Readiness">Shows whether identity, gas, and settlement funds are available. Fix red or amber items before attempting payments.</Definition><Definition icon={<Radar />} title="Start here">A three-step checklist: verify, fund, then run the first payment.</Definition><Definition icon={<CirclePause />} title="Review queue">Only payments requiring a human decision appear here. Approving inbound money clears its ledger quarantine; it does not send money back.</Definition><Definition icon={<Landmark />} title="Cash position">Compares cleared incoming money with committed outgoing money so Assay can prevent reserve-policy breaches.</Definition></div>
        </GuideSection>

        <GuideSection id="decisions" eyebrow="Plain-language states" title="What ALLOW, HOLD, ESCALATE, and BLOCK mean">
          <div className="overflow-hidden rounded-2xl border border-white/10"><Decision name="ALLOW" tone="text-emerald-300" meaning="The payment fits your operating policy." result="An outbound payment proceeds to Cleanverse and settlement. An inbound payment becomes cleared." /><Decision name="HOLD" tone="text-amber-300" meaning="Moving money now would breach a reserve or operating rule." result="No outbound transfer occurs. A finance operator reviews it." /><Decision name="ESCALATE" tone="text-amber-300" meaning="Signals combine into an unusual pattern—for example, a large amount from a new party." result="The payment enters the review queue with an explanation." /><Decision name="BLOCK" tone="text-red-300" meaning="Cleanverse says the wallet or asset is not eligible." result="The transfer does not execute. Assay cannot override compliance." /></div>
        </GuideSection>

        <GuideSection id="payments" eyebrow="The money loop" title="Receive, review, and pay">
          <h3 className="text-xl font-black">Receiving money</h3><p>For initial faucet funding, send Circle Monad-testnet USDC to the Cleanverse deposit address shown in Workspace Readiness; Cleanverse converts it into aUSDC at the workspace wallet. For a later inbound-payment demo, send existing aUSDC directly to the workspace wallet and press <strong>Sync inbound transfers</strong>.</p>
          <h3 className="mt-8 text-xl font-black">Paying a supplier</h3><p>Enter a recipient wallet and decimal aUSDC amount. Assay first evaluates cash policy, then calls Cleanverse verification, then signs the on-chain transfer. A result message confirms settlement, review, or compliance failure.</p>
          <h3 className="mt-8 text-xl font-black">Reviewing an exception</h3><p><strong>Approve</strong> accepts the operating risk. Outbound approvals recheck compliance and settle. Inbound approvals only mark already-arrived funds as cleared. <strong>Reject</strong> closes the review without initiating a transfer.</p>
        </GuideSection>

        <GuideSection id="audit" eyebrow="Evidence" title="Every decision stays explainable">
          <p>The activity table links the payment, risk signals, Assay decision, Cleanverse status, and transaction hash. When Cleanverse has indexed the transaction, the compliance report link appears alongside it.</p><div className="mt-7 flex items-start gap-4 rounded-2xl border border-[#a8d14a]/30 bg-[#a8d14a]/10 p-5"><FileDown className="mt-1 h-6 w-6 shrink-0 text-[#a8d14a]" /><div><h3 className="text-lg font-black">Export from the workspace header</h3><p className="mt-2 text-base leading-7 text-zinc-300">JSON preserves the complete structured record. CSV is easier for finance teams to open in spreadsheets. Both exports are scoped to the signed-in workspace owner.</p></div></div>
        </GuideSection>

        <GuideSection id="troubleshooting" eyebrow="When something is not green" title="Troubleshooting">
          <Trouble problem="A‑Pass does not exist" fix="Press Verify identity and complete the Cleanverse page. If the link fails, ask Cleanverse to enable A‑Pass generation or hosted verification for Assay’s sandbox API ID." /><Trouble problem="0.0000 MON" fix="Use the Monad testnet faucet and send MON directly to the displayed workspace wallet." /><Trouble problem="0 aUSDC after using Circle" fix="Confirm Circle was set to USDC on Monad Testnet and that you pasted the Cleanverse deposit address, not the workspace wallet. If Circle USDC reached the deposit address but aUSDC remains zero after waiting, contact Cleanverse with the transaction hash." /><Trouble problem="A payout remains held" fix="Open the review queue and read the stated reserve or anomaly reason. Approve only if you understand the exception." /><Trouble problem="No inbound payment appears" fix="Press Sync inbound transfers. Confirm the token was the configured Cleanverse USD contract on Monad testnet, not ordinary USDC." />
          <Callout icon={<KeyRound />} title="Security boundary">Managed wallets are suitable for testnet demonstrations. Real-value production requires an embedded wallet, external signer, or scoped smart-account session key plus independent security review.</Callout>
        </GuideSection>
      </main>
    </div>
  </div>;
}

function GuideSection({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-28 border-b border-white/10 py-14 last:border-0"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-[#a8d14a]">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{title}</h2><div className="mt-6 text-base leading-8 text-zinc-300">{children}</div></section>; }
function Instruction({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <div className="grid gap-3 border-b border-white/10 pb-4 sm:grid-cols-[44px_1fr]"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#a8d14a] text-sm font-black text-zinc-950">{number}</span><div><h3 className="text-lg font-black text-white">{title}</h3><p className="mt-1 text-base leading-7 text-zinc-300">{children}</p></div></div>; }
function Definition({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <div className="border-l-2 border-[#a8d14a] pl-5"><span className="text-[#a8d14a] [&>svg]:h-5 [&>svg]:w-5">{icon}</span><h3 className="mt-4 text-xl font-black text-white">{title}</h3><p className="mt-2 text-base leading-7 text-zinc-300">{children}</p></div>; }
function Decision({ name, tone, meaning, result }: { name: string; tone: string; meaning: string; result: string }) { return <div className="grid gap-2 border-b border-white/10 p-5 last:border-0 sm:grid-cols-[120px_1fr]"><strong className={`text-base ${tone}`}>{name}</strong><div><p className="text-white">{meaning}</p><p className="mt-1 text-sm text-zinc-400">Result: {result}</p></div></div>; }
function Trouble({ problem, fix }: { problem: string; fix: string }) { return <div className="border-b border-white/10 py-5"><h3 className="flex items-center gap-2 text-lg font-black text-white"><HelpCircle className="h-5 w-5 text-[#a8d14a]" />{problem}</h3><p className="mt-2 text-base leading-7 text-zinc-300">{fix}</p></div>; }
function Callout({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <div className="mt-8 flex gap-4 rounded-2xl border border-amber-400/30 bg-amber-400/10 p-5"><span className="mt-1 text-amber-300 [&>svg]:h-6 [&>svg]:w-6">{icon}</span><div><h3 className="text-lg font-black text-white">{title}</h3><p className="mt-2 text-base leading-7 text-zinc-300">{children}</p></div></div>; }
